// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwnPeVB99DnBeRNAe7n28hdnnPW7AvLfQ',
    appId: '1:242869855489:web:87d0e0e9afcc3298042700',
    messagingSenderId: '242869855489',
    projectId: 'brew-crew-aa629',
    authDomain: 'brew-crew-aa629.firebaseapp.com',
    storageBucket: 'brew-crew-aa629.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDIjEXUL2ECYriFhF3t8iyrxFFk-3FMB0',
    appId: '1:242869855489:android:4868d2a7a196c2cc042700',
    messagingSenderId: '242869855489',
    projectId: 'brew-crew-aa629',
    storageBucket: 'brew-crew-aa629.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhJSsRPg7nkeFVDNyO2LUpV-fduqka9PA',
    appId: '1:242869855489:ios:f34adec34046ad89042700',
    messagingSenderId: '242869855489',
    projectId: 'brew-crew-aa629',
    storageBucket: 'brew-crew-aa629.appspot.com',
    iosClientId: '242869855489-i0ab87vpvjoiea90m8bpd1n0im4178ll.apps.googleusercontent.com',
    iosBundleId: 'com.example.rebeg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhJSsRPg7nkeFVDNyO2LUpV-fduqka9PA',
    appId: '1:242869855489:ios:f34adec34046ad89042700',
    messagingSenderId: '242869855489',
    projectId: 'brew-crew-aa629',
    storageBucket: 'brew-crew-aa629.appspot.com',
    iosClientId: '242869855489-i0ab87vpvjoiea90m8bpd1n0im4178ll.apps.googleusercontent.com',
    iosBundleId: 'com.example.rebeg',
  );
}
